site_name: Cocorum Docs

theme:
  name: "material"
  logo: assets/cocorum_icon.png

plugins:
  - mkdocstrings

nav:
  - Home: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - Reference:
    - modules_ref/cocorum_main.md
    - modules_ref/cocorum_chatapi.md
    - modules_ref/cocorum_servicephp.md
    - modules_ref/cocorum_uploadphp.md
    - modules_ref/cocorum_scraping.md
    - modules_ref/cocorum_jsonhandles.md
    - modules_ref/cocorum_utils.md
    - modules_ref/cocorum_static.md
  - explanation.md
