site_name: Cocorum Docs

theme:
  name: "material"
  logo: assets/cocorum_icon.png

plugins:
  - mkdocstrings

nav:
  - Home: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md
